- .github/workflows/dev-deploy.yml
- Dockerfile
- src/main/java/woohakdong/server/TestController.java
개발 서버 ci/cd pipeline을 수행하는 github action을 작성하였다.
1. 배포가 정상적으로 이루어지는 지를 확인하기 위한 /test 엔드포인트를 작성하였다.
1. develop 브랜치로 Push 되는 코드 변경 사항을 Tracking한다.
2. 변경 사항에 대해 ARM 기반, AMD 기반 Docker Image로 빌드하고, ECR로 푸쉬한다.
3. ssh를 이용하여 EC2로 접속하여 ECR 로그인을 진행한다.
4. EC2에 작성된 docker-compose 파일을 새로운 이미지로 재실행한다.
> [WHD-24] CI/CD: Setup CI/CD pipeline for dev server deployment

- .github/workflows/test-deploy.yml
- Dockerfile
- src/main/java/woohakdong/server/common/config/SecurityConfig.java
- src/main/java/woohakdong/server/common/security/jwt/JWTFilter.java
- src/main/resources/application.properties
- src/test/java/woohakdong/server/WoohakdongServerApplicationTests.java
1. Dockerfile 추가
2. application.properties 수정 ( docker-compose에 맞게 )
1. Security Filter에서 permitAll 엔드포인트 변경
`/login` -> `/v1/auth/login/social`
4. JWT Filter에서 import 관련 오류 해결
5. Test 코드 임시 비활성화
> Securitytest deploy

- build.gradle
- src/main/java/woohakdong/server/common/config/S3Config.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/common/exception/CustomException.java
- src/main/java/woohakdong/server/common/exception/ErrorResponseBody.java
- src/main/java/woohakdong/server/common/exception/GlobalExceptionHandler.java
- src/main/resources/application.properties
- src/main/resources/application.yml
Spring에서 S3 관련 기능을 사용할 수 있도록 환경 설정 및 기본 예외 처리 핸들러 추가
1. S3 의존성 추가
2. GlobalExceptionHandler 추가
> [WHD-27] FEAT: Setup S3 Config

- build.gradle
- src/main/java/woohakdong/server/common/config/SecurityConfig.java
Spring에서 Security 관련 기능을 사용할 수 있도록 환경 설정
Spring Security 의존성 추가
SecurityConfig 추가
> [WHD-80] Feat: setup spring security

- .github/workflows/dev-deploy.yml
- src/main/java/woohakdong/server/api/controller/auth/AuthController.java
- src/main/java/woohakdong/server/domain/club/Club.java
- src/main/java/woohakdong/server/domain/club/ClubRepository.java
- src/main/java/woohakdong/server/domain/gathering/Gathering.java
- src/main/java/woohakdong/server/domain/gathering/GatheringRepository.java
- src/main/java/woohakdong/server/domain/gathering/GatheringType.java
- src/main/java/woohakdong/server/domain/school/School.java
- src/test/java/woohakdong/server/domain/club/ClubRepositoryTest.java
- src/test/java/woohakdong/server/domain/gathering/GatheringRepositoryTest.java
Club, Gathering Entity 추가 및 Persistence Layer 테스트 코드 작성
1. Club Entity 작성 및 테스트 코드 작성
2. Gathering Entity 작성 테스트 코드 작성
[WHD-98]
skip deploy
[WHD-98]: https://8901dev.atlassian.net/browse/WHD-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-98] Feat : Make club, gathering entity

- src/main/java/woohakdong/server/api/controller/club/ClubController.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubInfoResponse.java
- src/main/java/woohakdong/server/api/service/club/ClubService.java
- src/main/java/woohakdong/server/domain/club/Club.java
- src/test/java/woohakdong/server/api/service/club/ClubServiceTest.java
- Club 엔티티에 clubGeneration Column 추가
- Club 엔티티에 기수를 뜻하는 clubGeneration Column 추가
- 테스트 코드 작성
[WHD-99]
[WHD-99]: https://8901dev.atlassian.net/browse/WHD-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-99] Feat: Add clubGeneration Column to club

- src/main/java/woohakdong/server/api/controller/club/ClubController.java
- src/main/java/woohakdong/server/api/controller/club/ClubControllerDocs.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubCreateRequest.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubInfoResponse.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubJoinGatheringInfoResponse.java
- src/main/java/woohakdong/server/api/service/club/ClubService.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/domain/club/Club.java
- src/main/java/woohakdong/server/domain/clubmember/ClubMemberRepository.java
- src/test/java/woohakdong/server/api/service/club/ClubServiceTest.java
1. 동아리 정보 불러오는 api 구현
2. 동아리 등록을 위한 모임 정보 불러오는 api 구현
1. 동아리 Entity에 column 추가 ( clubGeneration, clubDues )
2. 이후 주문 정보에 포함 될 gatheringId를 제공하는 api 구현
[WHD-100]
[WHD-100]: https://8901dev.atlassian.net/browse/WHD-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-100] Feat: Implement Club and JOIN Gathering get api

- src/main/java/woohakdong/server/api/controller/clubMember/ClubMemberController.java
- src/main/java/woohakdong/server/api/controller/clubMember/ClubMemberControllerDocs.java
- src/main/java/woohakdong/server/api/controller/clubMember/dto/ClubMemberInfoResponse.java
- src/main/java/woohakdong/server/api/controller/member/MemberController.java
- src/main/java/woohakdong/server/api/controller/member/MemberControllerDocs.java
- src/main/java/woohakdong/server/api/service/clubMember/ClubMemberService.java
- src/main/java/woohakdong/server/domain/clubmember/ClubMemberRepository.java
- src/test/java/woohakdong/server/api/service/clubMember/ClubMemberServiceTest.java
- Club member list api 개발
- club member list를 기수별로 조회할 수 있다.
- 테스트 코드 작성
[WHD-118](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-118)
skip deploy
[WHD-118]: https://8901dev.atlassian.net/browse/WHD-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-118] Feat: Add club member list api and test

- src/main/java/woohakdong/server/api/service/bank/MockBankService.java
- src/main/java/woohakdong/server/api/service/club/ClubService.java
- src/main/java/woohakdong/server/common/data/DataInitializer.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/domain/admin/adminAccount/AccountType.java
- src/main/java/woohakdong/server/domain/admin/adminAccount/AdminAccount.java
- src/main/java/woohakdong/server/domain/admin/adminAccount/AdminAccountRepository.java
- src/main/java/woohakdong/server/domain/admin/adminAccountHistory/AdminAccountHistory.java
- src/main/java/woohakdong/server/domain/admin/adminAccountHistory/AdminAccountHistoryRepository.java
- src/main/java/woohakdong/server/domain/clubAccount/ClubAccount.java
- src/main/java/woohakdong/server/domain/clubAccountHistory/ClubAccountHistory.java
- src/main/java/woohakdong/server/domain/clubAccountHistory/ClubAccountHistoryRepository.java
- src/main/resources/application.yml
- src/test/java/woohakdong/server/api/service/bank/MockBankServiceTest.java
- src/test/java/woohakdong/server/domain/clubAccount/ClubAccountRepositoryTest.java
- 동아리 계좌로 회비를 이체 하는 로직
- Admin 계좌에서 club 계좌로 회비를 이체 한다.
- 테스트 코드 작성
[WHD-124](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-124)
skip deploy
[WHD-124]: https://8901dev.atlassian.net/browse/WHD-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD 124] Feat: Add transfer to club

- src/main/java/woohakdong/server/common/config/WebConfig.java
CORS 관련 설정 변경
- 웹 브라우저 origin에 대해 http에서 https로 변경
[WHD-170]
[WHD-170]: https://8901dev.atlassian.net/browse/WHD-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-170] Fix: Change origin name

- src/main/java/woohakdong/server/api/controller/item/ItemController.java
- src/main/java/woohakdong/server/api/controller/item/ItemControllerDocs.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemListResponse.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemRegisterRequest.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemRegisterResponse.java
- src/main/java/woohakdong/server/api/service/item/ItemService.java
- src/main/java/woohakdong/server/domain/ItemHistory/ItemHistory.java
- src/main/java/woohakdong/server/domain/ItemHistory/ItemHistoryRepository.java
- src/main/java/woohakdong/server/domain/item/Item.java
- src/main/java/woohakdong/server/domain/item/ItemCategory.java
- src/main/java/woohakdong/server/domain/item/ItemRepository.java
- src/test/java/woohakdong/server/api/service/item/ItemServiceTest.java
물품 등록 및 리스트 조회
- 물품 등록 api
- 물품 리스트 조회 api
[WHD-158](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-158), [WHD-163](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-163)
[WHD-158]: https://8901dev.atlassian.net/browse/WHD-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WHD-163]: https://8901dev.atlassian.net/browse/WHD-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-158] Feat: Add item basic api

- src/main/java/woohakdong/server/api/controller/item/ItemController.java
- src/main/java/woohakdong/server/api/controller/item/ItemControllerDocs.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemBorrowResponse.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemHistoryResponse.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemReturnRequest.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemReturnResponse.java
- src/main/java/woohakdong/server/api/service/item/ItemService.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/domain/ItemHistory/ItemHistory.java
- src/main/java/woohakdong/server/domain/ItemHistory/ItemHistoryRepository.java
- src/main/java/woohakdong/server/domain/item/Item.java
- src/main/java/woohakdong/server/domain/item/ItemRepository.java
- src/test/java/woohakdong/server/api/service/item/ItemServiceTest.java
물품 대여 기능 구현
물품 반납 기능 구현
물품 대여 기록 리스트 확인 구현
- 물품이 사용중이 아니라면 대여할 수 있다.
- 물품을 반납할 수 있다.
- 물품 대여 기록을 조회할 수 있다.
[WHD-167](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-167)
[WHD-167]: https://8901dev.atlassian.net/browse/WHD-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-167] Feat: item borrow return api

- .github/workflows/dev-deploy.yml
- build.gradle
- src/main/java/woohakdong/server/api/controller/club/dto/ClubCreateRequest.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubJoinGroupInfoResponse.java
- src/main/java/woohakdong/server/api/service/club/ClubService.java
- src/main/java/woohakdong/server/api/service/email/EmailClient.java
- src/main/java/woohakdong/server/api/service/email/EmailClientImpl.java
- src/main/java/woohakdong/server/api/service/email/EmailService.java
- src/main/java/woohakdong/server/api/service/order/OrderService.java
- src/main/java/woohakdong/server/common/config/AsyncConfig.java
- src/main/java/woohakdong/server/common/config/BatchWarningConfig.java
- src/main/java/woohakdong/server/common/config/RetryConfig.java
- src/main/java/woohakdong/server/common/data/DataInitializer.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/domain/group/Group.java
- src/main/resources/application-sentry.yml
- src/main/resources/application.yml
- src/test/java/woohakdong/server/api/service/club/ClubServiceTest.java
- src/test/java/woohakdong/server/api/service/email/EmailServiceTest.java
- src/test/java/woohakdong/server/api/service/order/OrderServiceTest.java
- src/test/java/woohakdong/server/domain/group/GroupRepositoryTest.java
- 신규 동아리원이 동아리 가입 시, 이메일로 동아리 관련 정보를 전송한다.
- SMTP 관련 의존성 및 Config 설정
- 이메일 발송 실패 시, 총 3회까지 반복
- 이메일 발송 시, 비동기로 진행
- 비동기, 재시도를 위한 의존성 및 Config 설정
- 테스트 코드 작성
[WHD-153]
[WHD-153]: https://8901dev.atlassian.net/browse/WHD-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-153] Feat: Implement email logic

- src/main/java/woohakdong/server/api/controller/item/ItemController.java
- src/main/java/woohakdong/server/api/controller/item/ItemControllerDocs.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemAvailableUpdateRequest.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemUpdateRequest.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemUpdateResponse.java
- src/main/java/woohakdong/server/api/service/item/ItemService.java
- src/main/java/woohakdong/server/domain/item/Item.java
- src/main/java/woohakdong/server/domain/item/ItemRepository.java
- src/test/java/woohakdong/server/api/service/item/ItemServiceTest.java
물품 수정, 삭제, 검색할 수 있다.
물품 수정
물품 삭제
물품 사용 가능 여부 수정
물품 카테고리, 이름으로 검색
WHD-173(https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-173)
> [WHD-173] Feat: Add item update, delete, search api

- src/main/java/woohakdong/server/api/controller/schedule/ScheduleController.java
- src/main/java/woohakdong/server/api/controller/schedule/ScheduleControllerDocs.java
- src/main/java/woohakdong/server/api/controller/schedule/dto/ScheduleCreateRequest.java
- src/main/java/woohakdong/server/api/controller/schedule/dto/ScheduleIdResponse.java
- src/main/java/woohakdong/server/api/controller/schedule/dto/ScheduleInfoResponse.java
- src/main/java/woohakdong/server/api/controller/schedule/dto/ScheduleUpdateRequest.java
- src/main/java/woohakdong/server/api/service/schedule/ScheduleService.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/domain/club/ClubRepository.java
- src/main/java/woohakdong/server/domain/club/ClubRepositoryImpl.java
- src/main/java/woohakdong/server/domain/schedule/Schedule.java
- src/main/java/woohakdong/server/domain/schedule/ScheduleJpaRepository.java
- src/main/java/woohakdong/server/domain/schedule/ScheduleRepository.java
- src/main/java/woohakdong/server/domain/schedule/ScheduleRepositoryImpl.java
- src/test/java/woohakdong/server/api/service/schedule/ScheduleServiceTest.java
- src/test/java/woohakdong/server/domain/club/ClubRepositoryTest.java
- 일정 등록, 수정, 삭제, 조회
- 일정 단건 조회
- 일정 리스트 조회
- 일정 수정
- 일정 삭제
- 일정 CRUD 관련 테스트 작성
[WHD-198]
[WHD-198]: https://8901dev.atlassian.net/browse/WHD-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-198] Feat: Schedule api

- src/main/java/woohakdong/server/api/controller/admin/auth/AdminAuthController.java
- src/main/java/woohakdong/server/api/controller/admin/auth/AdminAuthControllerDocs.java
- src/main/java/woohakdong/server/api/controller/admin/auth/dto/AdminInfoResponse.java
- src/main/java/woohakdong/server/api/controller/admin/auth/dto/AdminInfoUpdateRequest.java
- src/main/java/woohakdong/server/api/controller/admin/auth/dto/AdminJoinRequest.java
- src/main/java/woohakdong/server/api/controller/admin/auth/dto/AdminLoginRequest.java
- src/main/java/woohakdong/server/api/controller/auth/dto/LoginResponse.java
- src/main/java/woohakdong/server/api/controller/member/dto/MemberInfoResponse.java
- src/main/java/woohakdong/server/api/service/admin/auth/AdminAuthService.java
- src/main/java/woohakdong/server/api/service/member/MemberService.java
- src/main/java/woohakdong/server/common/config/SecurityConfig.java
- src/main/java/woohakdong/server/common/data/DataInitializer.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/domain/member/Member.java
- src/main/java/woohakdong/server/domain/member/MemberJpaRepository.java
- src/main/java/woohakdong/server/domain/member/MemberRepository.java
- src/main/java/woohakdong/server/domain/member/MemberRepositoryImpl.java
- src/main/java/woohakdong/server/domain/refreshToken/RefreshToken.java
- src/test/java/woohakdong/server/api/service/admin/auth/AdminAuthServiceTest.java
- 관리자 로그인 api
- 관리자 등록 api
- 관리자 정보 수정 api
- 관리자 정보 불러오기 api
- jwt를 이용한 관리자 로그인
- 관리자를 등록할 수 있다.
- 관리자의 정보를 수정할 수 있다.
- 관리자의 정보를 불러올 수 있다.
[WHD-208](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-208)
[WHD-208]: https://8901dev.atlassian.net/browse/WHD-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-208] Feat: admin login api

- src/main/java/woohakdong/server/api/controller/notification/NotificationController.java
- src/main/java/woohakdong/server/api/controller/notification/NotificationControllerDocs.java
- src/main/java/woohakdong/server/api/service/email/EmailClient.java
- src/main/java/woohakdong/server/api/service/email/EmailClientImpl.java
- src/main/java/woohakdong/server/api/service/email/EmailService.java
- src/main/java/woohakdong/server/api/service/notification/NotificationService.java
- src/main/java/woohakdong/server/api/service/order/OrderService.java
- src/main/java/woohakdong/server/domain/club/Club.java
- src/main/java/woohakdong/server/domain/schedule/Schedule.java
- src/test/java/woohakdong/server/api/service/email/EmailServiceTest.java
- src/test/java/woohakdong/server/api/service/notification/NotificationServiceTest.java
- 동아리 정보를 담은 이메일 전송
- 동아리 일정 정보를 담은 이메일 전송
- 동아리 정보를 바탕으로 동아리원들에게 이메일을 전송한다.
- 동아리 일정 정보를 바탕으로 동아리원들에게 이메일을 전송한다.
- Schedule 엔티티의 Cascade 옵션 제거
[WHD-228]
[WHD-228]: https://8901dev.atlassian.net/browse/WHD-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-228] Feat: Notification with email

- src/main/java/woohakdong/server/api/controller/club/ClubController.java
- src/main/java/woohakdong/server/api/controller/club/ClubControllerDocs.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubAccountResponse.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubCreateResponse.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubHistoryTermResponse.java
- src/main/java/woohakdong/server/api/controller/club/dto/ClubIdResponse.java
- src/main/java/woohakdong/server/api/controller/group/dto/GroupJoinOrderResponse.java
- src/main/java/woohakdong/server/api/controller/group/dto/PaymentInfoResponse.java
- src/main/java/woohakdong/server/api/service/club/ClubService.java
- src/main/java/woohakdong/server/api/service/order/OrderService.java
- src/main/java/woohakdong/server/api/service/order/PaymentClient.java
- src/main/java/woohakdong/server/api/service/order/PortOnePaymentClient.java
- src/main/java/woohakdong/server/common/data/DataInitializer.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/domain/admin/adminAccount/AdminAccount.java
- src/main/java/woohakdong/server/domain/admin/adminAccount/AdminAccountRepository.java
- src/main/java/woohakdong/server/domain/admin/adminAccount/AdminAccountRepositoryImpl.java
- src/main/java/woohakdong/server/domain/admin/adminAccountHistory/AdminAccountHistory.java
- src/main/java/woohakdong/server/domain/club/Club.java
- src/main/java/woohakdong/server/domain/clubAccount/ClubAccount.java
- src/main/java/woohakdong/server/domain/clubHistory/ClubHistory.java
- src/main/java/woohakdong/server/domain/clubmember/ClubMember.java
- src/main/java/woohakdong/server/domain/group/Group.java
- src/main/java/woohakdong/server/domain/group/GroupType.java
- src/main/java/woohakdong/server/domain/order/Order.java
- src/main/java/woohakdong/server/domain/payment/Payment.java
- src/test/java/woohakdong/server/api/service/club/ClubServiceTest.java
- src/test/java/woohakdong/server/api/service/order/OrderServiceTest.java
- Order 엔티티 필드에 OrderName, OrderDescription 추가
- **기존 Order 정보의 정합성 이슈 해결**
기존의 구조에서는 Order의 정보를 연관되어 있는 Group으로부터 가져왔다.
따라서 Group의 정보가 변경될 때, 기존의 Order들의 데이터를 변경시키지 않게 하기 위해서 새로운 Group을 생성하였다.
이를 반정규화를 통해 Order에 생성되는 시점의 Group의 정보를 중복으로 저장함으로써, Order의 정보의 정합성을 지켰다.
- clubService 리팩토링
- clubService 테스트 코드 추가
[WHD-235]
skip deploy
[WHD-235]: https://8901dev.atlassian.net/browse/WHD-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-235] Fix: Change Order data format

- src/main/java/woohakdong/server/api/controller/clubMember/ClubMemberController.java
- src/main/java/woohakdong/server/api/controller/clubMember/ClubMemberControllerDocs.java
- src/main/java/woohakdong/server/api/controller/item/ItemController.java
- src/main/java/woohakdong/server/api/controller/item/ItemControllerDocs.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemBorrowedResponse.java
- src/main/java/woohakdong/server/api/controller/item/dto/ItemHistoryResponse.java
- src/main/java/woohakdong/server/api/service/clubMember/ClubMemberService.java
- src/main/java/woohakdong/server/api/service/item/ItemService.java
- src/main/java/woohakdong/server/common/exception/CustomErrorInfo.java
- src/main/java/woohakdong/server/domain/ItemHistory/ItemHistoryJpaRepository.java
- src/main/java/woohakdong/server/domain/ItemHistory/ItemHistoryRepository.java
- src/main/java/woohakdong/server/domain/ItemHistory/ItemHistoryRepositoryImpl.java
- src/main/java/woohakdong/server/domain/itemBorrowed/ItemBorrowed.java
- src/main/java/woohakdong/server/domain/itemBorrowed/ItemBorrowedJpaRepository.java
- src/main/java/woohakdong/server/domain/itemBorrowed/ItemBorrowedRepository.java
- src/main/java/woohakdong/server/domain/itemBorrowed/ItemBorrowedRepositoryImpl.java
- src/test/java/woohakdong/server/api/service/item/ItemServiceTest.java
- 회원별 물품 대여기록 반환 api
- 자신이 빌린 물품 목록 반환 api
- itemHistory table에서 Member로 회원별 물품 대여기록 반환 로직 작성
- ItemBorrowed라는 테이블을 두어 clubMember 별 현재 빌리고 있는 item을 추적하도록 로직 작성
[WHD-234](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-234)
[WHD-234]: https://8901dev.atlassian.net/browse/WHD-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-234] Feat: item clubmember list api

- src/main/java/woohakdong/server/api/controller/admin/auth/AdminAuthController.java
- src/main/java/woohakdong/server/api/controller/dues/dto/ClubAccountHistoryListResponse.java
- src/main/java/woohakdong/server/api/service/club/ClubService.java
- src/main/java/woohakdong/server/api/service/dues/DuesService.java
- src/main/java/woohakdong/server/common/data/DataInitializer.java
- src/main/java/woohakdong/server/domain/clubAccount/ClubAccount.java
- 회비 사용 내역 nh로 부터 불러오는 api 초기 세팅 수정
- clubAccount 등록 시 최근 업데이트 시간 해당 첫 분기로 초기화
- admin Url 수정
[WHD-237](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-237)
[WHD-237]: https://8901dev.atlassian.net/browse/WHD-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [WHD-237] Fix: get dues list to nh api

- src/main/java/woohakdong/server/api/controller/admin/auth/AdminAuthControllerDocs.java
- src/main/java/woohakdong/server/api/controller/admin/overall/AdminOverallController.java
- src/main/java/woohakdong/server/api/controller/admin/overall/AdminOverallControllerDocs.java
- src/main/java/woohakdong/server/api/controller/admin/overall/dto/ClubListResponse.java
- src/main/java/woohakdong/server/api/controller/admin/overall/dto/CountResponse.java
- src/main/java/woohakdong/server/api/controller/admin/overall/dto/SchoolListResponse.java
- src/main/java/woohakdong/server/api/controller/admin/school/AdminSchoolController.java
- src/main/java/woohakdong/server/api/controller/admin/school/AdminSchoolControllerDocs.java
- src/main/java/woohakdong/server/api/service/admin/club/AdminSchoolService.java
- src/main/java/woohakdong/server/api/service/admin/overall/AdminOverallService.java
- src/main/java/woohakdong/server/domain/club/ClubJpaRepository.java
- src/main/java/woohakdong/server/domain/club/ClubRepository.java
- src/main/java/woohakdong/server/domain/club/ClubRepositoryImpl.java
- src/main/java/woohakdong/server/domain/item/ItemJpaRepository.java
- src/main/java/woohakdong/server/domain/item/ItemRepository.java
- src/main/java/woohakdong/server/domain/item/ItemRepositoryImpl.java
- src/main/java/woohakdong/server/domain/member/MemberJpaRepository.java
- src/main/java/woohakdong/server/domain/member/MemberRepository.java
- src/main/java/woohakdong/server/domain/member/MemberRepositoryImpl.java
- src/main/java/woohakdong/server/domain/school/SchoolRepository.java
- src/main/java/woohakdong/server/domain/school/SchoolRepositoryImpl.java
- src/test/java/woohakdong/server/api/service/admin/club/AdminSchoolServiceTest.java
- src/test/java/woohakdong/server/api/service/admin/overall/AdminOverallServiceTest.java
- 관리자는 우학동의 전체적인 통계를 확인할 수 있다.
- 관리자는 우학동의 학교별 통계를 확인할 수 있다.
- 우학동에 등록된 동아리 수를 반환
- 우학동의 등록된 학교 수 반환
- 우학동에 등록된 물품 수 반환
- 우학동에 등록된 학교 리스트 반환
- 우학동에 등록된 동아리 리스트 반환
- 학교별 등록된 동아리 수 반환
- 학교별 등록한 회원 수 반환
- 학교별 등록한 물품 수 반환
- 학교별 동아리 리스트 반환
[WHD-209](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-209)
[WHD-209]: https://8901dev.atlassian.net/browse/WHD-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-209] Feat: admin club statistics

- src/main/java/woohakdong/server/api/controller/item/ItemController.java
- src/main/java/woohakdong/server/api/controller/item/ItemControllerDocs.java
- src/main/java/woohakdong/server/api/service/item/ItemService.java
- src/test/java/woohakdong/server/api/service/item/ItemServiceTest.java
- 연체 여부로 물품 리스트를 반환한다.
- 연체 여부로 물품 리스트를 반환한다.
[WHD-265](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-265)
[WHD-265]: https://8901dev.atlassian.net/browse/WHD-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-265] Feat: add item list by overdue

- src/main/java/woohakdong/server/api/service/bank/MockBankService.java
- src/main/java/woohakdong/server/api/service/email/EmailClient.java
- src/main/java/woohakdong/server/api/service/email/EmailClientImpl.java
- src/main/java/woohakdong/server/api/service/email/EmailService.java
- src/main/java/woohakdong/server/api/service/item/ItemOverdueNotificationService.java
- src/main/java/woohakdong/server/api/service/notification/NotificationService.java
- src/main/java/woohakdong/server/common/config/SchedulingConfig.java
- src/main/java/woohakdong/server/domain/itemBorrowed/ItemBorrowedJpaRepository.java
- src/main/java/woohakdong/server/domain/itemBorrowed/ItemBorrowedRepository.java
- src/main/java/woohakdong/server/domain/itemBorrowed/ItemBorrowedRepositoryImpl.java
- 매일 특정 시간마다 연체된 물품을 반납 알림 기능
- 매일 특정 시간마다 ItemBorrowed 테이블에서 연체된 물품을 반납 알림
[WHD-250](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-250)
[WHD-250]: https://8901dev.atlassian.net/browse/WHD-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-250] Feat: add item overdue notification

- src/main/java/woohakdong/server/api/service/admin/overall/AdminOverallService.java
- src/test/java/woohakdong/server/api/service/admin/overall/AdminOverallServiceTest.java
- 동아리별 결제 금액을 분기별로 반환한다.
- 동아리별 결제 금액을 분기별로 반환한다.
[WHD-284](https://8901dev.atlassian.net/browse/WHD-284)
[WHD-284]: https://8901dev.atlassian.net/browse/WHD-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-284] Refactor: admin club payment

- src/main/java/woohakdong/server/api/controller/inquiry/InquiryController.java
- src/main/java/woohakdong/server/api/controller/inquiry/InquiryControllerDocs.java
- src/main/java/woohakdong/server/api/controller/inquiry/dto/InquiryRequest.java
- src/main/java/woohakdong/server/api/controller/inquiry/dto/InquiryResponse.java
- src/main/java/woohakdong/server/api/service/inquiry/InquiryService.java
- src/main/java/woohakdong/server/domain/inquiry/Inquiry.java
- src/main/java/woohakdong/server/domain/inquiry/InquiryCategory.java
- src/main/java/woohakdong/server/domain/inquiry/InquiryJpaRepository.java
- src/main/java/woohakdong/server/domain/inquiry/InquiryRepository.java
- src/main/java/woohakdong/server/domain/inquiry/InquiryRepositoryImpl.java
- src/main/java/woohakdong/server/domain/item/ItemCategory.java
- src/main/java/woohakdong/server/domain/member/Member.java
- src/test/java/woohakdong/server/api/service/inquiry/InquiryServiceTest.java
- 문의를 등록한다
- 자신의 문의 리스트를 반환한다.
- 문의를 등록한다
- 자신의 문의 리스트를 반환한다.
[WHD-274](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-274)
[WHD-274]: https://8901dev.atlassian.net/browse/WHD-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-274] Feat: inquiry api

- .github/workflows/prod-deploy.yml
- main으로 push 및 pr시 woohakdong-manifests의 이미지를 업데이트 한다.
- main으로 push 및 pr시 woohakdong-manifests의 이미지를 업데이트 한다.
[WHD-286](https://8901dev.atlassian.net/jira/software/projects/WHD/boards/1?selectedIssue=WHD-286)
[WHD-286]: https://8901dev.atlassian.net/browse/WHD-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-286] cicd: prod ci

- src/main/java/woohakdong/server/api/controller/group/GroupController.java
- src/main/java/woohakdong/server/api/controller/group/GroupControllerDocs.java
- src/main/java/woohakdong/server/api/service/group/GroupService.java
- src/main/java/woohakdong/server/api/service/order/OrderService.java
- src/main/java/woohakdong/server/domain/clubmember/ClubMemberJpaRepository.java
- src/main/java/woohakdong/server/domain/clubmember/ClubMemberRepository.java
- src/main/java/woohakdong/server/domain/clubmember/ClubMemberRepositoryImpl.java
- src/main/java/woohakdong/server/domain/group/Group.java
- src/main/java/woohakdong/server/domain/groupmember/GroupMemberRepository.java
- src/main/java/woohakdong/server/domain/groupmember/GroupMemberRepositoryImpl.java
- src/test/java/woohakdong/server/api/service/group/GroupServiceTest.java
- src/test/java/woohakdong/server/api/service/group/GroupServiceTransTest.java
- src/test/java/woohakdong/server/api/service/order/OrderServiceTest.java
그룹에 가입된 동아리 멤버들의 목록 조회
- 그룹에 가입된 동아리 멤버들의 목록을 조회할 수 있다.
- EVENT 그룹 가입 관련 오류 수정
[WHD-288]
[WHD-288]: https://8901dev.atlassian.net/browse/WHD-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [WHD-288] Feat: Get group member list
